export const MENU_Menu = "MENU_Menu"; //菜单数据
export const NAV_AddNav = "NAV_AddNav"; //增加选项卡
export const NAV_DelNav = "NAV_DelNav"; //删除选项卡
export const NAV_CleanNav = "NAV_CleanNav"; //清空选项卡
export const NAV_Dom = "NAV_Dom"; //修改选项卡颜色
export const MENU_Change_Head_Show = "MENU_Change_Head_Show"; //修改头部隐藏显示
export const NAV_TabHandle= "NAV_TabHandle"; //修改头部隐藏显示
export const MENU_SET_CONTENTHEIGHT = 'MENU_SET_CONTENTHEIGHT'; //设置内容高度
export const BASIS_MAX_LENGTH = 'BASIS_MAX_LENGTH'; //基础数据-码表长度控制
export const DEVICE_CODE = 'DEVICE_CODE'; //车辆-车辆主数据数据传递
